const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94710136994"
const SESSION_ID = "PRABATH-MD~HUsVhSwL#r_na2dokQOpj3ZuffCVUSEm-7N41mil9vzCCNUbJjy8"
const GITHUB_USERNAME = "Vajiramd1"

module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID,
 GITHUB_USERNAME
}
