name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      SESSION_ID: PRABATH-MD~2SR1zbJT#AuP26cxLlYkpW6d_bmo6li0yCcN3R1_JoF0ewuJESAM
      GITHUB_AUTH_TOKEN: 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
      BOT_NUMBER: 94710136994

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start
